version: '3.8'

services:
  # Service pour l'entraînement du modèle avec données synthétiques
  train:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./logs:/app/logs
    command: python -m src.scripts.train_model --use-synthetic --model-dir /app/models --output-dir /app/data/processed
    environment:
      - PYTHONPATH=/app

  # Service pour générer des prédictions
  predict:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./predictions:/app/predictions
      - ./logs:/app/logs
    depends_on:
      - train
    command: python -m src.scripts.generate_predictions --data-file /app/data/processed/synthetic_hospital_data.csv --model-dir /app/models --output-dir /app/predictions --days 30
    environment:
      - PYTHONPATH=/app

  # Service pour la validation du modèle
  validate:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./validation_results:/app/validation_results
    depends_on:
      - train
    command: python -m src.scripts.validate_model --model-path /app/models --data-file /app/data/processed/synthetic_hospital_data.csv --output-dir /app/validation_results
    environment:
      - PYTHONPATH=/app

volumes:
  data:
  models:
  predictions:
  logs:
  validation_results: